# Generated by Django 6.0.6 on 2026-06-20 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="documents/", verbose_name="Файл документа")),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "Новый"), ("APPROVED", "Одобрен"), ("REJECTED", "Отклонен")],
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус верификации",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True,
                        help_text="Укажите причину отказа или важные заметки при проверке",
                        null=True,
                        verbose_name="Комментарий администратора",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-created_at"],
            },
        ),
    ]
