name: Django CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ob3_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:4.0-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run Django System Checks and Tests with Coverage
      env:
        SECRET_KEY: "django-insecure-github-actions-test-key"
        DEBUG: "True"
        DB_NAME: "ob3_db"
        DB_USER: "postgres"
        DB_PASSWORD: "postgres"
        DB_HOST: "localhost"
        DB_PORT: "5432"
        CELERY_BROKER_URL: "redis://localhost:6379/0"
        CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
      run: |
        poetry run python manage.py check
        poetry run coverage run manage.py test apps.documents
        poetry run coverage report

    # Наводим финальный лоск: проверяем только стиль форматирования black
    - name: Check Code Quality Style
      run: |
        poetry run black . --check
